# Generated by Django 4.2.2 on 2023-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_pageviews_remove_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('film', 'Film'), ('book', 'Book'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
