# Generated by Django 4.2.2 on 2023-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
